version: 0.2
phases:
  pre_build:
    commands:
      - echo "Enetred the prebuild phase"
  build:
    commands:
      - echo "Entered the build phase"
      - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo "Entered the post build phase"
artifact:
  files:
    - target/beanstalk.example-0.0.1-SNAPSHOT/*
